server:
    port: 8300
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: customer-service
                  uri: http://localhost:8100/
                  predicates:
                      - Path=/Customers/**
                - id: product-service
                  uri: http://localhost:8200/
                  predicates:
                      - Path=/Products/**
eureka:
    client:
        serviceUrl:
            defaultZone: http://test:test@localhost:8090/eureka
